import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";

import Image from "next/image";
import SessionWrapper from "./components/SessionWrapper";
import { Toaster } from "sonner";
import ProviderWrapper from "./components/ProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  weight: "400", // Pacifico only has weight 400
  subsets: ["latin"],
  variable: "--font-pacifico-mono",
});

export const metadata: Metadata = {
  title: "Postremami",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico} antialiased`}
      >
        <SessionWrapper>
          <ProviderWrapper>
            <main className="max-w-7xl mx-auto">
              <div className="bg-black">
                <Image
                  src={"/hero6.jpg"}
                  alt="hero"
                  fill
                  className="object-cover h-[20px] -z-10 brightness-60"
                />
              </div>
              {children}
            </main>
          </ProviderWrapper>
        </SessionWrapper>
        <Toaster />
      </body>
    </html>
  );
}
// [#cc858a];
// [#d7b19e]
// [#e8d2ae];
